#name: Laravel
#
#on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
#
#jobs:
#  laravel-tests:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
#        with:
#          php-version: '8.1.8'
#      - uses: actions/checkout@v3
#      - name: Copy .env
#        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
#      - name: Install Dependencies
#        run: |
#          composer config http-basic.nova.laravel.com ${{ secrets.NOVA_USERNAME }} ${{ secrets.NOVA_PASSWORD }}
#          composer install --no-dev --no-ansi --no-interaction --no-scripts --no-progress
#      # composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
#      - name: Generate key
#        run: php artisan key:generate
#      - name: Directory Permissions
#        run: chmod -R 777 storage bootstrap/cache
#      - name: Create Database
#        run: |
#          mkdir -p database
#          touch database/database.sqlite
#      - name: Cache clear
#        run: |
#          pwd
#          ./artisan opti:clear
#      - name: PHPUnit
#        env:
#          DB_CONNECTION: sqlite
#          DB_DATABASE: database/database.sqlite
#        run: |
#          ./artisan test
#
#
#
#name: Deploy
#
#on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
#
#jobs:
#  deploy:
#
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: true
#      matrix:
#        php: [8.1.8]
#        laravel: [9.0]
#
#    name: P${{ matrix.php }} - L${{ matrix.laravel }}
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v1
#
#      - name: Setup PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: ${{ matrix.php }}
#          ini-values: post_max_size=256M
#          extensions: xml, pcov
#          #          dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
#          tools: composer:v2, pecl
#          coverage: none
#
#      - name: Install dependencies
#        run: |
#          composer config http-basic.nova.laravel.com ${{ secrets.NOVA_USERNAME }} ${{ secrets.NOVA_PASSWORD }}
#          composer install --no-dev --no-ansi --no-interaction --no-scripts --no-progress
#      - name: Execute tests
#        run: vendor/bin/phpunit --verbose




name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.1.8]
        laravel: [9.0]

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install dependencies
        run: |
          composer config http-basic.nova.laravel.com ${{ secrets.NOVA_USERNAME }} ${{ secrets.NOVA_PASSWORD }}
          composer require "illuminate/contracts=^${{ matrix.laravel }}" --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Execute tests
        run: vendor/bin/phpunit --verbose

