name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.1.8]
        laravel: [9.0]

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: laravel-phpunit-action
        uses: nathanheffley/laravel-phpunit-action@master


      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: post_max_size=256M
          extensions: xml, pcov
          #          dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          tools: composer:v2, pecl
          coverage: none

      - name: Install dependencies
        run: |
          composer config http-basic.nova.laravel.com ${{ secrets.NOVA_USERNAME }} ${{ secrets.NOVA_PASSWORD }}
          composer install --no-dev --no-ansi --no-interaction --no-scripts --no-progress

      - name: Execute tests
        env:
          APP_ENV: testing
        run: ./vendor/bin/phpunit

